### PR TITLE
Dynamic tick-interval for x-axis in MC Sim

### PR DESCRIPTION
**Pull request by maqqju**
Modified the tick-interval for the monte carlo simulation so that, when the range of outcomes in the frequency table is high, the x-axis labels remain legible.

### CODE REVIEW

**Comment by nbrown02** [comment]
Thanks again for this 👍  Is it just for the When Will It Be Done chart? 
I tried loading just now and can still see it on the chart below...

**Comment by maqqju** [comment]
Nothing huge should change. When my MC generated a lot of different permutations, the labels were too cluttered to be read.

Try it out with data that has the following format:

`var data = ['null','null','null','null','null','null','null','null',1,'null',5,'null',].map((tp) => { return { countofcompleteddate : tp, numberofremainingitems : tp === 'null'? 'null' :250}});`

Since TP data is low, and the backlog size is considerably high, the range of the outcomes is widely spread (if I'm not mistaken between 0 and 800 days).

**Comment by nbrown02** [comment]
So just loaded data using the new .pbit - this is what I see:

Screenshot 2022-08-04 at 16 01 40

**Comment by maqqju** [comment]
Awesome - I'll fix the one below too (i tried it out on the When)...and resubmit the PR

**Comment by maqqju** [comment]
@nbrown02 - can you try again and see if it's better?

**Comment by nbrown02** [comment]
Looks good :) 

image

Going to merge now 👍

**Review by nbrown02 — APPROVED** [review]
Looks great!

**Pull request merged**
